import { MigrationInterface, QueryRunner } from "typeorm";

export class SchemaUpdate1786631123746 implements MigrationInterface {
    name = 'SchemaUpdate1786631123746'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "SubscriptionPlans" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "Name" character varying(100) NOT NULL, "BillingCycle" character varying(30) NOT NULL, "Price" numeric(18,2) NOT NULL DEFAULT '0', "AnnualPrice" numeric(18,2) NOT NULL DEFAULT '0', "DurationDays" integer NOT NULL, "IsActive" boolean NOT NULL DEFAULT true, "Features" text, CONSTRAINT "PK_5ff75cf72420e5c2614b500bf23" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4adcd6403b1efb8c1607f0261f" ON "SubscriptionPlans" ("Name") `);
        await queryRunner.query(`CREATE TABLE "UserPermissions" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UserId" uuid NOT NULL, "PermissionId" uuid NOT NULL, "GrantedByUserId" uuid, "GrantedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_UserPermissions_UserId_PermissionId" UNIQUE ("UserId", "PermissionId"), CONSTRAINT "PK_1e123371e61f260cdbb158d892a" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39042b6a776bff78ecebefd27a" ON "UserPermissions" ("UserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_085946d7405623321c24d7b510" ON "UserPermissions" ("PermissionId") `);
        await queryRunner.query(`CREATE TABLE "Permissions" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "Code" character varying(100) NOT NULL, "Name" character varying(150) NOT NULL, "Module" character varying(100), "Description" character varying(255), CONSTRAINT "PK_99fa50928aea3ac88937056e3dd" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5a432f132904ca5b29e77bb7c3" ON "Permissions" ("Code") `);
        await queryRunner.query(`CREATE TABLE "RolePermissions" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "RoleId" uuid NOT NULL, "PermissionId" uuid NOT NULL, CONSTRAINT "UQ_RolePermissions_RoleId_PermissionId" UNIQUE ("RoleId", "PermissionId"), CONSTRAINT "PK_1c70a2b6073a1fffcc1de748423" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb751e799c75213a525cee8fc4" ON "RolePermissions" ("RoleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_97f3b8eab22442a4ce38ff101d" ON "RolePermissions" ("PermissionId") `);
        await queryRunner.query(`CREATE TABLE "Roles" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "Name" character varying(100) NOT NULL, "Description" character varying(255), CONSTRAINT "PK_04f7be88261f9d1e55675c0ee75" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ad152fb549a5b88dccaaf3a101" ON "Roles" ("Name") `);
        await queryRunner.query(`CREATE TABLE "RefreshTokens" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UserId" uuid NOT NULL, "TokenHash" character varying(255) NOT NULL, "ExpiresAt" TIMESTAMP NOT NULL, "RevokedAt" TIMESTAMP, "ReplacedByTokenId" uuid, "IpAddress" character varying(100), "UserAgent" character varying(500), CONSTRAINT "PK_e38718d3725050cca1a208f1800" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a221a29de1aaaed494dd36930a" ON "RefreshTokens" ("UserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ae23a6c9266f3115d1ce7722bd" ON "RefreshTokens" ("TokenHash") `);
        await queryRunner.query(`CREATE TABLE "AuditLogs" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid, "UserId" uuid, "Action" character varying(50) NOT NULL, "EntityName" character varying(100), "EntityId" character varying(100), "IpAddress" character varying(100), "UserAgent" character varying(500), "Metadata" text, CONSTRAINT "PK_668928ee58e31388b5871273307" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c44780c2364d646aba7440c13" ON "AuditLogs" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a72fc60b4d31b30b779014a788" ON "AuditLogs" ("UserId") `);
        await queryRunner.query(`CREATE TABLE "Customers" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "FullName" character varying(200) NOT NULL, "ContactPerson" character varying(200), "Email" character varying(150), "Phone" character varying(50), "Address" character varying(300), "TIN" character varying(50), "Notes" character varying(255), "Balance" numeric(18,2) NOT NULL DEFAULT '0', "Status" character varying(30) NOT NULL DEFAULT 'active', CONSTRAINT "PK_21d71058eb01aa3ddaa0ababea3" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f6b817423d6ef6f968586b79cd" ON "Customers" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d657ccc9154b6e466812b94dbb" ON "Customers" ("FullName") `);
        await queryRunner.query(`CREATE TABLE "ProductCategories" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "Code" character varying(50), "Name" character varying(150) NOT NULL, "Description" character varying(255), "Status" character varying(30) NOT NULL DEFAULT 'active', "DeletedAt" TIMESTAMP, CONSTRAINT "PK_196dbfd676dfc95e3d91b0f63b7" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b3c37fbb62589ca2cb51791a4" ON "ProductCategories" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0488466066e9532e2226b2138e" ON "ProductCategories" ("Name") `);
        await queryRunner.query(`CREATE TABLE "InventoryTransactions" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "TransactionNumber" character varying(50) NOT NULL, "ProductId" uuid NOT NULL, "VendorId" uuid, "InvoiceId" uuid, "SourceId" uuid, "SourceNumber" character varying(100), "CreatedByUserId" uuid, "TransactionType" character varying(30) NOT NULL, "Quantity" numeric(18,3) NOT NULL, "PreviousStock" numeric(18,3) NOT NULL, "NewStock" numeric(18,3) NOT NULL, "UnitCost" numeric(18,2), "Reference" character varying(100), "Reason" character varying(255), "Notes" character varying(255), "IsReversal" boolean NOT NULL DEFAULT false, "ReversalOfTransactionId" uuid, "ReversalBatchId" character varying(100), CONSTRAINT "PK_e0c8ca1261f46cdcd075403bea8" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c4d407934b27438c43a8d6e1c" ON "InventoryTransactions" ("BusinessId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e54cbd46c896c7bd0200bde3ed" ON "InventoryTransactions" ("TransactionNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_08fd663f01f4c7d31298fa206a" ON "InventoryTransactions" ("ProductId") `);
        await queryRunner.query(`CREATE INDEX "IDX_961e52da3feed089691822949e" ON "InventoryTransactions" ("VendorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d5edcd4703a0e489756da1398" ON "InventoryTransactions" ("InvoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa019466dd4b2453d1c0c4213d" ON "InventoryTransactions" ("SourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_470a90f524106598d0ffdfef94" ON "InventoryTransactions" ("CreatedByUserId") `);
        await queryRunner.query(`CREATE TABLE "Products" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "CategoryId" uuid, "ProductName" character varying(200) NOT NULL, "SKU" character varying(100) NOT NULL, "Barcode" character varying(100), "Unit" character varying(50), "Description" character varying(500), "BuyingPrice" numeric(18,2) NOT NULL DEFAULT '0', "SellingPrice" numeric(18,2) NOT NULL DEFAULT '0', "CurrentStock" numeric(18,3) NOT NULL DEFAULT '0', "MinimumStock" numeric(18,3) NOT NULL DEFAULT '0', "ImageUrl" character varying(500), "LastStockMovementAt" TIMESTAMP, "Status" character varying(30) NOT NULL DEFAULT 'active', CONSTRAINT "PK_a70dbd7a49ef4bad9c0dc14cbd4" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e8ca26e84c826287cdaf1a43ad" ON "Products" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e907f7e9043ee05a2c99f8d51" ON "Products" ("CategoryId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_Products_BusinessId_SKU" ON "Products" ("BusinessId", "SKU") `);
        await queryRunner.query(`CREATE TABLE "SalesInvoiceItems" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "InvoiceId" uuid NOT NULL, "ProductId" uuid NOT NULL, "Quantity" numeric(18,3) NOT NULL, "UnitPrice" numeric(18,2) NOT NULL, "Discount" numeric(18,2) NOT NULL DEFAULT '0', "Tax" numeric(18,2) NOT NULL DEFAULT '0', "Total" numeric(18,2) NOT NULL, CONSTRAINT "PK_4b5bb6944867724377cab8013d0" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cac4f53b8e063d134aee49ab18" ON "SalesInvoiceItems" ("InvoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_20eeda6c308aefb3921f272266" ON "SalesInvoiceItems" ("ProductId") `);
        await queryRunner.query(`CREATE TABLE "LedgerAccounts" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid, "Code" character varying(50) NOT NULL, "Name" character varying(150) NOT NULL, "AccountType" character varying(30) NOT NULL, "NormalBalance" character varying(10), "IsSystem" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_8540944f31c36380b754c7b1a54" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4097789f476374193650e83d0a" ON "LedgerAccounts" ("BusinessId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_de461611a505e9242b6fedf7a3" ON "LedgerAccounts" ("Code") `);
        await queryRunner.query(`CREATE TABLE "LedgerEntries" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid, "AccountId" uuid NOT NULL, "InvoiceId" uuid, "SourceId" uuid, "SourceNumber" character varying(100), "PostingBatchId" character varying(100), "CreatedByUserId" uuid, "TransactionDate" TIMESTAMP NOT NULL DEFAULT now(), "PostingDate" TIMESTAMP NOT NULL DEFAULT now(), "SourceType" character varying(30) NOT NULL, "Reference" character varying(100), "Description" character varying(255), "Debit" numeric(18,2) NOT NULL DEFAULT '0', "Credit" numeric(18,2) NOT NULL DEFAULT '0', "IsReversal" boolean NOT NULL DEFAULT false, "ReversalOfEntryId" uuid, "ReversalBatchId" character varying(100), CONSTRAINT "PK_115a367aa289715693ac7dc0b08" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82fff24065a76e7823df61853e" ON "LedgerEntries" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5346af17267b7336c094b1b2c7" ON "LedgerEntries" ("AccountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a519c5d0f9a5b4fe5f8ae35498" ON "LedgerEntries" ("InvoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a84aa7276028687792674ed4b7" ON "LedgerEntries" ("SourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_23f49386a5dce43183770ea5bf" ON "LedgerEntries" ("CreatedByUserId") `);
        await queryRunner.query(`CREATE TABLE "SalesInvoices" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "CustomerId" uuid, "CreatedByUserId" uuid NOT NULL, "InvoiceNumber" character varying(50) NOT NULL, "PaymentMethod" character varying(30), "InvoiceDate" TIMESTAMP NOT NULL DEFAULT now(), "DueDate" date, "Subtotal" numeric(18,2) NOT NULL DEFAULT '0', "DiscountTotal" numeric(18,2) NOT NULL DEFAULT '0', "TaxTotal" numeric(18,2) NOT NULL DEFAULT '0', "TotalAmount" numeric(18,2) NOT NULL DEFAULT '0', "AmountPaid" numeric(18,2) NOT NULL DEFAULT '0', "Balance" numeric(18,2) NOT NULL DEFAULT '0', "Status" character varying(30) NOT NULL DEFAULT 'draft', "DocumentStatus" character varying(30) NOT NULL DEFAULT 'draft', "PaymentStatus" character varying(30) NOT NULL DEFAULT 'unpaid', "Notes" character varying(500), "PdfUrl" character varying(500), "CancelledAt" TIMESTAMP, "CancelledByUserId" uuid, "CancellationReason" character varying(500), CONSTRAINT "PK_6212c2a4a9d44cf75eee2fcddd7" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2d01c5130d93189d8a98741ca4" ON "SalesInvoices" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e733d3bace74e9903b7997c74" ON "SalesInvoices" ("CustomerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4485204bb97aca9485b17a6b99" ON "SalesInvoices" ("CreatedByUserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_SalesInvoices_BusinessId_InvoiceNumber" ON "SalesInvoices" ("BusinessId", "InvoiceNumber") `);
        await queryRunner.query(`CREATE TABLE "EmailOtps" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid, "UserId" uuid, "Email" character varying(150) NOT NULL, "Purpose" character varying(30) NOT NULL, "OtpHash" character varying(255) NOT NULL, "ExpiresAt" TIMESTAMP NOT NULL, "UsedAt" TIMESTAMP, "Attempts" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_3ac1163ea4cb2d98470da7160c6" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_03975301c6d0f0a9d06f19e3dc" ON "EmailOtps" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9a4ff0552329122afc8a20ee3" ON "EmailOtps" ("UserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_04a54605cb46c2dd6cb455d331" ON "EmailOtps" ("Email") `);
        await queryRunner.query(`CREATE TABLE "Users" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid, "RoleId" uuid NOT NULL, "FullName" character varying(200) NOT NULL, "Email" character varying(150) NOT NULL, "PasswordHash" character varying(255), "Status" character varying(30) NOT NULL DEFAULT 'inactive', "LastLoginAt" TIMESTAMP, "EmailVerifiedAt" TIMESTAMP, CONSTRAINT "PK_329bb2946729a51bd2b19a5159f" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6cff8f12ac332bca683d8de1ee" ON "Users" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1abb40f1fe8e092337c8f46d1c" ON "Users" ("RoleId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_884fdf47515c24dbbf6d89c2d8" ON "Users" ("Email") `);
        await queryRunner.query(`CREATE TABLE "SubscriptionPayments" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "SubscriptionId" uuid NOT NULL, "BusinessId" uuid NOT NULL, "PlanId" uuid NOT NULL, "Amount" numeric(18,2) NOT NULL DEFAULT '0', "PaymentMethod" character varying(100), "TransactionReference" character varying(150), "ProofPath" character varying(500), "Status" character varying(30) NOT NULL DEFAULT 'pending', "ReviewedBy" uuid, "ReviewedAt" TIMESTAMP, "RejectionReason" character varying(500), CONSTRAINT "PK_8c001727ab02d70525868f490cc" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a6ccb84a6b307d633d0466aed" ON "SubscriptionPayments" ("SubscriptionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_486fc8dd6955e865f4aef0f9c2" ON "SubscriptionPayments" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2ce31675bc94342b060fa19ae" ON "SubscriptionPayments" ("PlanId") `);
        await queryRunner.query(`CREATE TABLE "BusinessSubscriptions" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "PlanId" uuid NOT NULL, "StartDate" date NOT NULL, "EndDate" date NOT NULL, "GracePeriodDays" integer NOT NULL DEFAULT '0', "Status" character varying(30) NOT NULL DEFAULT 'pending', "AutoRenew" boolean NOT NULL DEFAULT false, "Notes" character varying(255), CONSTRAINT "PK_c72c4eae51119c74c622c1d2215" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3fec2337eefed0a32c3ffa066f" ON "BusinessSubscriptions" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f1f81cfa4c0785d8f821c2791" ON "BusinessSubscriptions" ("PlanId") `);
        await queryRunner.query(`CREATE TABLE "SystemSettings" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid, "SettingKey" character varying(150) NOT NULL, "SettingValue" text, "Category" character varying(100), "Description" character varying(255), CONSTRAINT "UQ_SystemSettings_BusinessId_Key" UNIQUE ("BusinessId", "SettingKey"), CONSTRAINT "PK_301ba3adf66ca04a65fb1b42069" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f53f795b4cff453f8ca2ed93a6" ON "SystemSettings" ("BusinessId") `);
        await queryRunner.query(`CREATE TABLE "Businesses" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessName" character varying(200) NOT NULL, "Logo" character varying(500), "Address" character varying(300), "Phone" character varying(50), "Email" character varying(150), "TIN" character varying(50), "Status" character varying(30) NOT NULL DEFAULT 'active', "ActiveSubscriptionId" uuid, "SubscriptionProofPath" character varying(500), CONSTRAINT "REL_8929242ef21b358a088c04ffba" UNIQUE ("ActiveSubscriptionId"), CONSTRAINT "PK_924008afa405d9e362b3e43a97e" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5bbe286a2dd01f9b412f76fbf4" ON "Businesses" ("BusinessName") `);
        await queryRunner.query(`CREATE TABLE "Vendors" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "Name" character varying(200) NOT NULL, "ContactPerson" character varying(200), "Email" character varying(150), "Phone" character varying(50), "Address" character varying(300), "TIN" character varying(50), "Notes" character varying(255), "Balance" numeric(18,2) NOT NULL DEFAULT '0', "Status" character varying(30) NOT NULL DEFAULT 'active', CONSTRAINT "PK_a4acda306be846cea7a7934e9b9" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d9d569aea60ee78a6c4b4a607d" ON "Vendors" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_77b8d96b0342036d46056a2b23" ON "Vendors" ("Name") `);
        await queryRunner.query(`CREATE TABLE "SalesReceiptAllocations" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "SalesReceiptId" uuid NOT NULL, "SalesInvoiceId" uuid NOT NULL, "AllocatedAmount" numeric(18,2) NOT NULL, CONSTRAINT "PK_de86ca70d33cb30d83a84aa772d" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc7173dac265126eff77d4a405" ON "SalesReceiptAllocations" ("SalesReceiptId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d68ed44a4c5624043d585c21e2" ON "SalesReceiptAllocations" ("SalesInvoiceId") `);
        await queryRunner.query(`CREATE TABLE "SalesReceipts" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "CustomerId" uuid NOT NULL, "CreatedByUserId" uuid NOT NULL, "PostedByUserId" uuid, "VoidedByUserId" uuid, "ReceiptNumber" character varying(50) NOT NULL, "ReceiptDate" TIMESTAMP NOT NULL DEFAULT now(), "PostingDate" TIMESTAMP, "PaymentMethod" character varying(30), "CashOrBankAccountId" uuid, "Amount" numeric(18,2) NOT NULL DEFAULT '0', "ReferenceNumber" character varying(100), "Remarks" character varying(500), "Status" character varying(30) NOT NULL DEFAULT 'draft', "IsAutomatic" boolean NOT NULL DEFAULT false, "PostedAt" TIMESTAMP, "VoidedAt" TIMESTAMP, "VoidReason" character varying(500), CONSTRAINT "PK_c9305a5a0ae06e48e00489b05c9" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75fe8070ace0d77da0eb12acaa" ON "SalesReceipts" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7613cc0292f57b2c4e4c021aa" ON "SalesReceipts" ("CustomerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ffde96915fa4dcbe5f3c39e83" ON "SalesReceipts" ("CreatedByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a2f7c618dfdc06d6ec2accc71" ON "SalesReceipts" ("PostedByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f48d66986d659f02ac6da947d2" ON "SalesReceipts" ("VoidedByUserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_SalesReceipts_BusinessId_Number" ON "SalesReceipts" ("BusinessId", "ReceiptNumber") `);
        await queryRunner.query(`CREATE TABLE "PurchaseInvoiceItems" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "PurchaseInvoiceId" uuid NOT NULL, "ProductId" uuid, "Description" character varying(255), "Quantity" numeric(18,3) NOT NULL, "UnitCost" numeric(18,2) NOT NULL, "DiscountAmount" numeric(18,2) NOT NULL DEFAULT '0', "TaxRate" numeric(18,2) NOT NULL DEFAULT '0', "TaxAmount" numeric(18,2) NOT NULL DEFAULT '0', "LineSubtotal" numeric(18,2) NOT NULL, "LineTotal" numeric(18,2) NOT NULL, "IsInventoryItem" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b8b770185f719acb96f4bb3012a" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_784aaef37d4636a8307fe40f26" ON "PurchaseInvoiceItems" ("PurchaseInvoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_24ae34f508be40d71635a4160a" ON "PurchaseInvoiceItems" ("ProductId") `);
        await queryRunner.query(`CREATE TABLE "PurchaseInvoices" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "VendorId" uuid NOT NULL, "CreatedByUserId" uuid NOT NULL, "PostedByUserId" uuid, "CancelledByUserId" uuid, "ReversedByUserId" uuid, "PurchaseInvoiceNumber" character varying(50) NOT NULL, "VendorInvoiceNumber" character varying(100), "InvoiceDate" TIMESTAMP NOT NULL DEFAULT now(), "PostingDate" TIMESTAMP, "DueDate" date, "CurrencyCode" character varying(10) NOT NULL DEFAULT 'TZS', "ExchangeRate" numeric(18,6) NOT NULL DEFAULT '1', "Subtotal" numeric(18,2) NOT NULL DEFAULT '0', "DiscountTotal" numeric(18,2) NOT NULL DEFAULT '0', "TaxTotal" numeric(18,2) NOT NULL DEFAULT '0', "TotalAmount" numeric(18,2) NOT NULL DEFAULT '0', "AmountPaid" numeric(18,2) NOT NULL DEFAULT '0', "Balance" numeric(18,2) NOT NULL DEFAULT '0', "DocumentStatus" character varying(30) NOT NULL DEFAULT 'draft', "PaymentStatus" character varying(30) NOT NULL DEFAULT 'unpaid', "Remarks" character varying(500), "PostedAt" TIMESTAMP, "CancelledAt" TIMESTAMP, "CancellationReason" character varying(500), "ReversedAt" TIMESTAMP, "ReversalDate" date, "ReversalReason" character varying(500), "ReversalNumber" character varying(50), CONSTRAINT "PK_aef7156d9b7f01b6fa642b69753" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56fe009bc85b5b70f7baf92c85" ON "PurchaseInvoices" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5eac9e3d095596c814103ba325" ON "PurchaseInvoices" ("VendorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba4c3e2658f7548064d235df43" ON "PurchaseInvoices" ("CreatedByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_45bd61b1bb9562bd8b88a9c2e1" ON "PurchaseInvoices" ("PostedByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9265f1536055460af325eeb3d" ON "PurchaseInvoices" ("CancelledByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2200e731b9a372846d3340de1" ON "PurchaseInvoices" ("ReversedByUserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_PurchaseInvoices_BusinessId_Number" ON "PurchaseInvoices" ("BusinessId", "PurchaseInvoiceNumber") `);
        await queryRunner.query(`CREATE TABLE "PaymentVoucherAllocations" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "PaymentVoucherId" uuid NOT NULL, "PurchaseInvoiceId" uuid NOT NULL, "AllocatedAmount" numeric(18,2) NOT NULL, CONSTRAINT "PK_1d6fb4edaa71767233dbb2e96a5" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c166f6d43afa8297fb9de202a7" ON "PaymentVoucherAllocations" ("PaymentVoucherId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb3684bbda62b18d5ba326db45" ON "PaymentVoucherAllocations" ("PurchaseInvoiceId") `);
        await queryRunner.query(`CREATE TABLE "PaymentVouchers" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid NOT NULL, "VendorId" uuid NOT NULL, "CreatedByUserId" uuid NOT NULL, "PostedByUserId" uuid, "VoidedByUserId" uuid, "VoucherNumber" character varying(50) NOT NULL, "PaymentDate" TIMESTAMP NOT NULL DEFAULT now(), "PostingDate" TIMESTAMP, "PaymentMethod" character varying(30), "CashOrBankAccountId" uuid, "Amount" numeric(18,2) NOT NULL DEFAULT '0', "ReferenceNumber" character varying(100), "Remarks" character varying(500), "Status" character varying(30) NOT NULL DEFAULT 'draft', "IsAutomatic" boolean NOT NULL DEFAULT false, "PostedAt" TIMESTAMP, "VoidedAt" TIMESTAMP, "VoidReason" character varying(500), CONSTRAINT "PK_927a94483fdd10465599fea80a1" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7939111718ef0c19b693af067" ON "PaymentVouchers" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e7c572f11299685a1bd8c4759" ON "PaymentVouchers" ("VendorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_67cf3490b1a42cef101bf1ac78" ON "PaymentVouchers" ("CreatedByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7364d60a4c88d66dd20b88cc31" ON "PaymentVouchers" ("PostedByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8303597b9a7d2583cc89f89ba" ON "PaymentVouchers" ("VoidedByUserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_PaymentVouchers_BusinessId_Number" ON "PaymentVouchers" ("BusinessId", "VoucherNumber") `);
        await queryRunner.query(`CREATE TABLE "NotificationReads" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UserId" uuid NOT NULL, "NotificationId" uuid NOT NULL, "ReadAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_NotificationReads_User_Notification" UNIQUE ("UserId", "NotificationId"), CONSTRAINT "PK_c9963bf216d565c89343824e178" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_850a89a29e81e48ff3ab58714c" ON "NotificationReads" ("UserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf4c39b103b07a61515c8f3e04" ON "NotificationReads" ("NotificationId") `);
        await queryRunner.query(`CREATE TABLE "DocumentCounters" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "CreatedAt" TIMESTAMP NOT NULL DEFAULT now(), "UpdatedAt" TIMESTAMP NOT NULL DEFAULT now(), "BusinessId" uuid, "DocumentType" character varying(50) NOT NULL, "Prefix" character varying(50) NOT NULL, "NextSequence" integer NOT NULL DEFAULT '1', "IncludeYear" boolean NOT NULL DEFAULT true, "Padding" integer NOT NULL DEFAULT '6', CONSTRAINT "UQ_DocumentCounters_BusinessId_DocumentType" UNIQUE ("BusinessId", "DocumentType"), CONSTRAINT "PK_f122b544b9aa842b3cd777c2f65" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6fc881cea30d6d97952456b013" ON "DocumentCounters" ("BusinessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f284e4ec929ca129f511fd716b" ON "DocumentCounters" ("DocumentType") `);
        await queryRunner.query(`ALTER TABLE "UserPermissions" ADD CONSTRAINT "FK_39042b6a776bff78ecebefd27a5" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserPermissions" ADD CONSTRAINT "FK_085946d7405623321c24d7b510b" FOREIGN KEY ("PermissionId") REFERENCES "Permissions"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RolePermissions" ADD CONSTRAINT "FK_bb751e799c75213a525cee8fc4c" FOREIGN KEY ("RoleId") REFERENCES "Roles"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RolePermissions" ADD CONSTRAINT "FK_97f3b8eab22442a4ce38ff101d8" FOREIGN KEY ("PermissionId") REFERENCES "Permissions"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RefreshTokens" ADD CONSTRAINT "FK_a221a29de1aaaed494dd36930a8" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AuditLogs" ADD CONSTRAINT "FK_a72fc60b4d31b30b779014a788b" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Customers" ADD CONSTRAINT "FK_f6b817423d6ef6f968586b79cd7" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProductCategories" ADD CONSTRAINT "FK_2b3c37fbb62589ca2cb51791a43" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" ADD CONSTRAINT "FK_3c4d407934b27438c43a8d6e1c1" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" ADD CONSTRAINT "FK_08fd663f01f4c7d31298fa206a8" FOREIGN KEY ("ProductId") REFERENCES "Products"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" ADD CONSTRAINT "FK_961e52da3feed089691822949e8" FOREIGN KEY ("VendorId") REFERENCES "Vendors"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" ADD CONSTRAINT "FK_8d5edcd4703a0e489756da13986" FOREIGN KEY ("InvoiceId") REFERENCES "SalesInvoices"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" ADD CONSTRAINT "FK_470a90f524106598d0ffdfef941" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Products" ADD CONSTRAINT "FK_e8ca26e84c826287cdaf1a43ad0" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Products" ADD CONSTRAINT "FK_7e907f7e9043ee05a2c99f8d51d" FOREIGN KEY ("CategoryId") REFERENCES "ProductCategories"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesInvoiceItems" ADD CONSTRAINT "FK_cac4f53b8e063d134aee49ab184" FOREIGN KEY ("InvoiceId") REFERENCES "SalesInvoices"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesInvoiceItems" ADD CONSTRAINT "FK_20eeda6c308aefb3921f2722665" FOREIGN KEY ("ProductId") REFERENCES "Products"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LedgerEntries" ADD CONSTRAINT "FK_5346af17267b7336c094b1b2c70" FOREIGN KEY ("AccountId") REFERENCES "LedgerAccounts"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LedgerEntries" ADD CONSTRAINT "FK_a519c5d0f9a5b4fe5f8ae354988" FOREIGN KEY ("InvoiceId") REFERENCES "SalesInvoices"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LedgerEntries" ADD CONSTRAINT "FK_23f49386a5dce43183770ea5bf5" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesInvoices" ADD CONSTRAINT "FK_2d01c5130d93189d8a98741ca45" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesInvoices" ADD CONSTRAINT "FK_2e733d3bace74e9903b7997c745" FOREIGN KEY ("CustomerId") REFERENCES "Customers"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesInvoices" ADD CONSTRAINT "FK_4485204bb97aca9485b17a6b994" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesInvoices" ADD CONSTRAINT "FK_1ae425bed20b5eb744fee375f60" FOREIGN KEY ("CancelledByUserId") REFERENCES "Users"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EmailOtps" ADD CONSTRAINT "FK_f9a4ff0552329122afc8a20ee34" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "FK_6cff8f12ac332bca683d8de1ee5" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Users" ADD CONSTRAINT "FK_1abb40f1fe8e092337c8f46d1c6" FOREIGN KEY ("RoleId") REFERENCES "Roles"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SubscriptionPayments" ADD CONSTRAINT "FK_7a6ccb84a6b307d633d0466aed5" FOREIGN KEY ("SubscriptionId") REFERENCES "BusinessSubscriptions"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SubscriptionPayments" ADD CONSTRAINT "FK_486fc8dd6955e865f4aef0f9c26" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SubscriptionPayments" ADD CONSTRAINT "FK_c2ce31675bc94342b060fa19aee" FOREIGN KEY ("PlanId") REFERENCES "SubscriptionPlans"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SubscriptionPayments" ADD CONSTRAINT "FK_42d6b03b06f99cd84cd0bf9a35d" FOREIGN KEY ("ReviewedBy") REFERENCES "Users"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "BusinessSubscriptions" ADD CONSTRAINT "FK_3fec2337eefed0a32c3ffa066fd" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "BusinessSubscriptions" ADD CONSTRAINT "FK_6f1f81cfa4c0785d8f821c2791c" FOREIGN KEY ("PlanId") REFERENCES "SubscriptionPlans"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SystemSettings" ADD CONSTRAINT "FK_f53f795b4cff453f8ca2ed93a67" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Businesses" ADD CONSTRAINT "FK_8929242ef21b358a088c04ffbaa" FOREIGN KEY ("ActiveSubscriptionId") REFERENCES "BusinessSubscriptions"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Vendors" ADD CONSTRAINT "FK_d9d569aea60ee78a6c4b4a607d5" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesReceiptAllocations" ADD CONSTRAINT "FK_dc7173dac265126eff77d4a405e" FOREIGN KEY ("SalesReceiptId") REFERENCES "SalesReceipts"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesReceiptAllocations" ADD CONSTRAINT "FK_d68ed44a4c5624043d585c21e25" FOREIGN KEY ("SalesInvoiceId") REFERENCES "SalesInvoices"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" ADD CONSTRAINT "FK_75fe8070ace0d77da0eb12acaa0" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" ADD CONSTRAINT "FK_b7613cc0292f57b2c4e4c021aa9" FOREIGN KEY ("CustomerId") REFERENCES "Customers"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" ADD CONSTRAINT "FK_4ffde96915fa4dcbe5f3c39e83a" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" ADD CONSTRAINT "FK_8a2f7c618dfdc06d6ec2accc711" FOREIGN KEY ("PostedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" ADD CONSTRAINT "FK_f48d66986d659f02ac6da947d2c" FOREIGN KEY ("VoidedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoiceItems" ADD CONSTRAINT "FK_784aaef37d4636a8307fe40f26c" FOREIGN KEY ("PurchaseInvoiceId") REFERENCES "PurchaseInvoices"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoiceItems" ADD CONSTRAINT "FK_24ae34f508be40d71635a4160a2" FOREIGN KEY ("ProductId") REFERENCES "Products"("Id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" ADD CONSTRAINT "FK_56fe009bc85b5b70f7baf92c85c" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" ADD CONSTRAINT "FK_5eac9e3d095596c814103ba3259" FOREIGN KEY ("VendorId") REFERENCES "Vendors"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" ADD CONSTRAINT "FK_ba4c3e2658f7548064d235df43d" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" ADD CONSTRAINT "FK_45bd61b1bb9562bd8b88a9c2e11" FOREIGN KEY ("PostedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" ADD CONSTRAINT "FK_f9265f1536055460af325eeb3d2" FOREIGN KEY ("CancelledByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" ADD CONSTRAINT "FK_d2200e731b9a372846d3340de10" FOREIGN KEY ("ReversedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PaymentVoucherAllocations" ADD CONSTRAINT "FK_c166f6d43afa8297fb9de202a77" FOREIGN KEY ("PaymentVoucherId") REFERENCES "PaymentVouchers"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PaymentVoucherAllocations" ADD CONSTRAINT "FK_bb3684bbda62b18d5ba326db45a" FOREIGN KEY ("PurchaseInvoiceId") REFERENCES "PurchaseInvoices"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" ADD CONSTRAINT "FK_a7939111718ef0c19b693af0671" FOREIGN KEY ("BusinessId") REFERENCES "Businesses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" ADD CONSTRAINT "FK_1e7c572f11299685a1bd8c4759e" FOREIGN KEY ("VendorId") REFERENCES "Vendors"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" ADD CONSTRAINT "FK_67cf3490b1a42cef101bf1ac78a" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" ADD CONSTRAINT "FK_7364d60a4c88d66dd20b88cc318" FOREIGN KEY ("PostedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" ADD CONSTRAINT "FK_c8303597b9a7d2583cc89f89ba8" FOREIGN KEY ("VoidedByUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "NotificationReads" ADD CONSTRAINT "FK_850a89a29e81e48ff3ab58714c4" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "NotificationReads" ADD CONSTRAINT "FK_cf4c39b103b07a61515c8f3e044" FOREIGN KEY ("NotificationId") REFERENCES "AuditLogs"("Id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "NotificationReads" DROP CONSTRAINT "FK_cf4c39b103b07a61515c8f3e044"`);
        await queryRunner.query(`ALTER TABLE "NotificationReads" DROP CONSTRAINT "FK_850a89a29e81e48ff3ab58714c4"`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" DROP CONSTRAINT "FK_c8303597b9a7d2583cc89f89ba8"`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" DROP CONSTRAINT "FK_7364d60a4c88d66dd20b88cc318"`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" DROP CONSTRAINT "FK_67cf3490b1a42cef101bf1ac78a"`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" DROP CONSTRAINT "FK_1e7c572f11299685a1bd8c4759e"`);
        await queryRunner.query(`ALTER TABLE "PaymentVouchers" DROP CONSTRAINT "FK_a7939111718ef0c19b693af0671"`);
        await queryRunner.query(`ALTER TABLE "PaymentVoucherAllocations" DROP CONSTRAINT "FK_bb3684bbda62b18d5ba326db45a"`);
        await queryRunner.query(`ALTER TABLE "PaymentVoucherAllocations" DROP CONSTRAINT "FK_c166f6d43afa8297fb9de202a77"`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" DROP CONSTRAINT "FK_d2200e731b9a372846d3340de10"`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" DROP CONSTRAINT "FK_f9265f1536055460af325eeb3d2"`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" DROP CONSTRAINT "FK_45bd61b1bb9562bd8b88a9c2e11"`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" DROP CONSTRAINT "FK_ba4c3e2658f7548064d235df43d"`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" DROP CONSTRAINT "FK_5eac9e3d095596c814103ba3259"`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoices" DROP CONSTRAINT "FK_56fe009bc85b5b70f7baf92c85c"`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoiceItems" DROP CONSTRAINT "FK_24ae34f508be40d71635a4160a2"`);
        await queryRunner.query(`ALTER TABLE "PurchaseInvoiceItems" DROP CONSTRAINT "FK_784aaef37d4636a8307fe40f26c"`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" DROP CONSTRAINT "FK_f48d66986d659f02ac6da947d2c"`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" DROP CONSTRAINT "FK_8a2f7c618dfdc06d6ec2accc711"`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" DROP CONSTRAINT "FK_4ffde96915fa4dcbe5f3c39e83a"`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" DROP CONSTRAINT "FK_b7613cc0292f57b2c4e4c021aa9"`);
        await queryRunner.query(`ALTER TABLE "SalesReceipts" DROP CONSTRAINT "FK_75fe8070ace0d77da0eb12acaa0"`);
        await queryRunner.query(`ALTER TABLE "SalesReceiptAllocations" DROP CONSTRAINT "FK_d68ed44a4c5624043d585c21e25"`);
        await queryRunner.query(`ALTER TABLE "SalesReceiptAllocations" DROP CONSTRAINT "FK_dc7173dac265126eff77d4a405e"`);
        await queryRunner.query(`ALTER TABLE "Vendors" DROP CONSTRAINT "FK_d9d569aea60ee78a6c4b4a607d5"`);
        await queryRunner.query(`ALTER TABLE "Businesses" DROP CONSTRAINT "FK_8929242ef21b358a088c04ffbaa"`);
        await queryRunner.query(`ALTER TABLE "SystemSettings" DROP CONSTRAINT "FK_f53f795b4cff453f8ca2ed93a67"`);
        await queryRunner.query(`ALTER TABLE "BusinessSubscriptions" DROP CONSTRAINT "FK_6f1f81cfa4c0785d8f821c2791c"`);
        await queryRunner.query(`ALTER TABLE "BusinessSubscriptions" DROP CONSTRAINT "FK_3fec2337eefed0a32c3ffa066fd"`);
        await queryRunner.query(`ALTER TABLE "SubscriptionPayments" DROP CONSTRAINT "FK_42d6b03b06f99cd84cd0bf9a35d"`);
        await queryRunner.query(`ALTER TABLE "SubscriptionPayments" DROP CONSTRAINT "FK_c2ce31675bc94342b060fa19aee"`);
        await queryRunner.query(`ALTER TABLE "SubscriptionPayments" DROP CONSTRAINT "FK_486fc8dd6955e865f4aef0f9c26"`);
        await queryRunner.query(`ALTER TABLE "SubscriptionPayments" DROP CONSTRAINT "FK_7a6ccb84a6b307d633d0466aed5"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "FK_1abb40f1fe8e092337c8f46d1c6"`);
        await queryRunner.query(`ALTER TABLE "Users" DROP CONSTRAINT "FK_6cff8f12ac332bca683d8de1ee5"`);
        await queryRunner.query(`ALTER TABLE "EmailOtps" DROP CONSTRAINT "FK_f9a4ff0552329122afc8a20ee34"`);
        await queryRunner.query(`ALTER TABLE "SalesInvoices" DROP CONSTRAINT "FK_1ae425bed20b5eb744fee375f60"`);
        await queryRunner.query(`ALTER TABLE "SalesInvoices" DROP CONSTRAINT "FK_4485204bb97aca9485b17a6b994"`);
        await queryRunner.query(`ALTER TABLE "SalesInvoices" DROP CONSTRAINT "FK_2e733d3bace74e9903b7997c745"`);
        await queryRunner.query(`ALTER TABLE "SalesInvoices" DROP CONSTRAINT "FK_2d01c5130d93189d8a98741ca45"`);
        await queryRunner.query(`ALTER TABLE "LedgerEntries" DROP CONSTRAINT "FK_23f49386a5dce43183770ea5bf5"`);
        await queryRunner.query(`ALTER TABLE "LedgerEntries" DROP CONSTRAINT "FK_a519c5d0f9a5b4fe5f8ae354988"`);
        await queryRunner.query(`ALTER TABLE "LedgerEntries" DROP CONSTRAINT "FK_5346af17267b7336c094b1b2c70"`);
        await queryRunner.query(`ALTER TABLE "SalesInvoiceItems" DROP CONSTRAINT "FK_20eeda6c308aefb3921f2722665"`);
        await queryRunner.query(`ALTER TABLE "SalesInvoiceItems" DROP CONSTRAINT "FK_cac4f53b8e063d134aee49ab184"`);
        await queryRunner.query(`ALTER TABLE "Products" DROP CONSTRAINT "FK_7e907f7e9043ee05a2c99f8d51d"`);
        await queryRunner.query(`ALTER TABLE "Products" DROP CONSTRAINT "FK_e8ca26e84c826287cdaf1a43ad0"`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" DROP CONSTRAINT "FK_470a90f524106598d0ffdfef941"`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" DROP CONSTRAINT "FK_8d5edcd4703a0e489756da13986"`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" DROP CONSTRAINT "FK_961e52da3feed089691822949e8"`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" DROP CONSTRAINT "FK_08fd663f01f4c7d31298fa206a8"`);
        await queryRunner.query(`ALTER TABLE "InventoryTransactions" DROP CONSTRAINT "FK_3c4d407934b27438c43a8d6e1c1"`);
        await queryRunner.query(`ALTER TABLE "ProductCategories" DROP CONSTRAINT "FK_2b3c37fbb62589ca2cb51791a43"`);
        await queryRunner.query(`ALTER TABLE "Customers" DROP CONSTRAINT "FK_f6b817423d6ef6f968586b79cd7"`);
        await queryRunner.query(`ALTER TABLE "AuditLogs" DROP CONSTRAINT "FK_a72fc60b4d31b30b779014a788b"`);
        await queryRunner.query(`ALTER TABLE "RefreshTokens" DROP CONSTRAINT "FK_a221a29de1aaaed494dd36930a8"`);
        await queryRunner.query(`ALTER TABLE "RolePermissions" DROP CONSTRAINT "FK_97f3b8eab22442a4ce38ff101d8"`);
        await queryRunner.query(`ALTER TABLE "RolePermissions" DROP CONSTRAINT "FK_bb751e799c75213a525cee8fc4c"`);
        await queryRunner.query(`ALTER TABLE "UserPermissions" DROP CONSTRAINT "FK_085946d7405623321c24d7b510b"`);
        await queryRunner.query(`ALTER TABLE "UserPermissions" DROP CONSTRAINT "FK_39042b6a776bff78ecebefd27a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f284e4ec929ca129f511fd716b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fc881cea30d6d97952456b013"`);
        await queryRunner.query(`DROP TABLE "DocumentCounters"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf4c39b103b07a61515c8f3e04"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_850a89a29e81e48ff3ab58714c"`);
        await queryRunner.query(`DROP TABLE "NotificationReads"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_PaymentVouchers_BusinessId_Number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8303597b9a7d2583cc89f89ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7364d60a4c88d66dd20b88cc31"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67cf3490b1a42cef101bf1ac78"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e7c572f11299685a1bd8c4759"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7939111718ef0c19b693af067"`);
        await queryRunner.query(`DROP TABLE "PaymentVouchers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb3684bbda62b18d5ba326db45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c166f6d43afa8297fb9de202a7"`);
        await queryRunner.query(`DROP TABLE "PaymentVoucherAllocations"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_PurchaseInvoices_BusinessId_Number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2200e731b9a372846d3340de1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9265f1536055460af325eeb3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45bd61b1bb9562bd8b88a9c2e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba4c3e2658f7548064d235df43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5eac9e3d095596c814103ba325"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56fe009bc85b5b70f7baf92c85"`);
        await queryRunner.query(`DROP TABLE "PurchaseInvoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24ae34f508be40d71635a4160a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_784aaef37d4636a8307fe40f26"`);
        await queryRunner.query(`DROP TABLE "PurchaseInvoiceItems"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_SalesReceipts_BusinessId_Number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f48d66986d659f02ac6da947d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a2f7c618dfdc06d6ec2accc71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ffde96915fa4dcbe5f3c39e83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7613cc0292f57b2c4e4c021aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75fe8070ace0d77da0eb12acaa"`);
        await queryRunner.query(`DROP TABLE "SalesReceipts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d68ed44a4c5624043d585c21e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc7173dac265126eff77d4a405"`);
        await queryRunner.query(`DROP TABLE "SalesReceiptAllocations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77b8d96b0342036d46056a2b23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9d569aea60ee78a6c4b4a607d"`);
        await queryRunner.query(`DROP TABLE "Vendors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bbe286a2dd01f9b412f76fbf4"`);
        await queryRunner.query(`DROP TABLE "Businesses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f53f795b4cff453f8ca2ed93a6"`);
        await queryRunner.query(`DROP TABLE "SystemSettings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f1f81cfa4c0785d8f821c2791"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fec2337eefed0a32c3ffa066f"`);
        await queryRunner.query(`DROP TABLE "BusinessSubscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2ce31675bc94342b060fa19ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_486fc8dd6955e865f4aef0f9c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a6ccb84a6b307d633d0466aed"`);
        await queryRunner.query(`DROP TABLE "SubscriptionPayments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_884fdf47515c24dbbf6d89c2d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1abb40f1fe8e092337c8f46d1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cff8f12ac332bca683d8de1ee"`);
        await queryRunner.query(`DROP TABLE "Users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04a54605cb46c2dd6cb455d331"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9a4ff0552329122afc8a20ee3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03975301c6d0f0a9d06f19e3dc"`);
        await queryRunner.query(`DROP TABLE "EmailOtps"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_SalesInvoices_BusinessId_InvoiceNumber"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4485204bb97aca9485b17a6b99"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e733d3bace74e9903b7997c74"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d01c5130d93189d8a98741ca4"`);
        await queryRunner.query(`DROP TABLE "SalesInvoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23f49386a5dce43183770ea5bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a84aa7276028687792674ed4b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a519c5d0f9a5b4fe5f8ae35498"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5346af17267b7336c094b1b2c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82fff24065a76e7823df61853e"`);
        await queryRunner.query(`DROP TABLE "LedgerEntries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de461611a505e9242b6fedf7a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4097789f476374193650e83d0a"`);
        await queryRunner.query(`DROP TABLE "LedgerAccounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20eeda6c308aefb3921f272266"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cac4f53b8e063d134aee49ab18"`);
        await queryRunner.query(`DROP TABLE "SalesInvoiceItems"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_Products_BusinessId_SKU"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e907f7e9043ee05a2c99f8d51"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8ca26e84c826287cdaf1a43ad"`);
        await queryRunner.query(`DROP TABLE "Products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_470a90f524106598d0ffdfef94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa019466dd4b2453d1c0c4213d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d5edcd4703a0e489756da1398"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_961e52da3feed089691822949e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08fd663f01f4c7d31298fa206a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e54cbd46c896c7bd0200bde3ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c4d407934b27438c43a8d6e1c"`);
        await queryRunner.query(`DROP TABLE "InventoryTransactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0488466066e9532e2226b2138e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b3c37fbb62589ca2cb51791a4"`);
        await queryRunner.query(`DROP TABLE "ProductCategories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d657ccc9154b6e466812b94dbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6b817423d6ef6f968586b79cd"`);
        await queryRunner.query(`DROP TABLE "Customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a72fc60b4d31b30b779014a788"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c44780c2364d646aba7440c13"`);
        await queryRunner.query(`DROP TABLE "AuditLogs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae23a6c9266f3115d1ce7722bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a221a29de1aaaed494dd36930a"`);
        await queryRunner.query(`DROP TABLE "RefreshTokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad152fb549a5b88dccaaf3a101"`);
        await queryRunner.query(`DROP TABLE "Roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97f3b8eab22442a4ce38ff101d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb751e799c75213a525cee8fc4"`);
        await queryRunner.query(`DROP TABLE "RolePermissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a432f132904ca5b29e77bb7c3"`);
        await queryRunner.query(`DROP TABLE "Permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_085946d7405623321c24d7b510"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39042b6a776bff78ecebefd27a"`);
        await queryRunner.query(`DROP TABLE "UserPermissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4adcd6403b1efb8c1607f0261f"`);
        await queryRunner.query(`DROP TABLE "SubscriptionPlans"`);
    }

}
