export const ROUTES = {
  landing: '/',
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  changePassword: '/change-password',
  dashboard: '/dashboard',
  invoices: '/invoices',
  invoiceCreate: '/invoices/new',
  purchaseInvoices: '/purchase-invoices',
  purchaseInvoiceCreate: '/purchase-invoices/new',
  salesReceipts: '/sales-receipts',
  salesReceiptCreate: '/sales-receipts/new',
  paymentVouchers: '/payment-vouchers',
  paymentVoucherCreate: '/payment-vouchers/new',
  audit: '/audit',
  settings: '/settings',
  admin: '/admin',
  adminBusinesses: '/admin/businesses',
  adminRevenue: '/admin/revenue',
  adminLoginAsBusiness: '/admin/login-as-business',
  reports: '/reports',
}
